// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DominioNomina.Modelos;

public partial class Credenciales
{
    public int IdCredencial { get; set; }

    public int IdUsuario { get; set; }

    public string Contrasenia { get; set; }

    public virtual Usuarios IdUsuarioNavigation { get; set; }
}