// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DominioNomina.Modelos;

public partial class Persona
{
    public int IdPersona { get; set; }

    public string Apellidos { get; set; }

    public string Nombres { get; set; }

    public int? Edad { get; set; }

    public string Genero { get; set; }

    public DateTime? FechaNacimiento { get; set; }

    public string LugarNacimiento { get; set; }
}