// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DominioNomina.Modelos;

public partial class Usuarios
{
    public int IdUsuario { get; set; }

    public string NombreUsuario { get; set; }

    public string CorreoUsuario { get; set; }

    public virtual ICollection<Credenciales> Credenciales { get; set; } = new List<Credenciales>();
}